#ifndef __MDESK_VERSION_H__
#define __MDESK_VERSION_H__

#define MDESK_VERSION         0x000200
#define MDESK_VERSION_MAJOR   0
#define MDESK_VERSION_MINOR   2
#define MDESK_PATCHLEVEL      0

#define MDESK_VERSION_DECIMAL 512
#define MDESK_VERSION_STRING  "0.2.0"

#endif /* __MDESK_VERSION_H__ */
